Repository suzuki-shunsuke/github-comment, pull requests merged in 2021-01, with the labels that each got.

#182 Don't use <pre><code> tags in hidden_combined_output
  pkg/template/template.go
Labels: bug

#183 fix: fix builtin template join_command and hidden_combined_output
  README.md
  pkg/api/exec.go
  pkg/api/post.go
  pkg/template/template.go
Labels: bug, documentation

#189 feat: support to hide comments
  .golangci.yml
  README.md
  go.mod
  go.sum
  pkg/api/exec.go
  pkg/api/post.go
  pkg/api/post_internal_test.go
  pkg/cmd/exec.go
  pkg/cmd/post.go
  pkg/comment/comment.go
  pkg/comment/mock.go
  pkg/comment/mutate.go
  pkg/config/config.go
  pkg/expr/expr.go
  pkg/option/exec.go
  pkg/option/post.go
Labels: documentation, enhancement

#190 feat: add log-level option and use logrus
  README.md
  go.mod
  go.sum
  pkg/api/exec.go
  pkg/api/post.go
  pkg/cmd/app.go
  pkg/cmd/exec.go
  pkg/cmd/post.go
  pkg/option/exec.go
  pkg/option/post.go
  pkg/signal/signal.go
Labels: enhancement

#192 docs: fix hide comments
  README.md
Labels: documentation

#193 fix: support to hide pull request comments
  pkg/comment/comment.go
Labels: bug

#195 fix(exec): set template key
  pkg/api/exec.go
  pkg/api/post.go
Labels: bug

#196 fix: post a comment even if it failed to list hidden comments
  pkg/api/exec.go
  pkg/api/post.go
Labels: bug

#198 fix: don't filter commits by login when login is empty
  pkg/api/post.go
Labels: bug

#199 fix: ignore error to get an authenticated user
  pkg/api/post.go
Labels: bug

#200 fix: rename "minimize" to "hide_old_comment"
  README.md
  pkg/api/exec.go
  pkg/api/post.go
  pkg/comment/comment.go
  pkg/comment/mutate.go
  pkg/config/config.go
  pkg/option/exec.go
  pkg/option/post.go
Labels: bug

#203 feat: remove color escape sequence
  go.mod
  go.sum
  pkg/execute/execute.go
Labels: enhancement

#207 refactor: remove an unused variable and fix an error message
  pkg/api/post.go
  pkg/constant/help.go
Labels: bug

#210 feat: add a command "hide" and embed meta data to comment
  pkg/api/comment.go
  pkg/api/exec.go
  pkg/api/hide.go
  pkg/api/post.go
  pkg/api/post_internal_test.go
  pkg/cmd/app.go
  pkg/cmd/hide.go
  pkg/config/config.go
  pkg/option/hide.go
  pkg/platform/platform.go
Labels: breaking change, enhancement

#212 fix: fix hide command
  pkg/api/hide.go
Labels: bug, enhancement

#211 docs: update README
  README.md
Labels: documentation

#213 fix: fix the validation of pull request number
  pkg/option/hide.go
  pkg/option/post.go
Labels: bug

#214 fix: validate hide parameters
  pkg/api/hide.go
Labels: bug

#215 feat: get the pull request number from CI_INFO_PR_NUMBER
  README.md
  pkg/platform/platform.go
Labels: documentation, enhancement
